import { createBlock, createConfig, createGroup, createPanel, createLabel } from './config.builder';
import { EditInterface, EditPlaintext } from './config.interfaces';

export default createConfig('http://47.89.8.92:3008/v1', 'draginoMNS')
	.setName('Gateway Manager')
    .addGroup( createGroup()
		.setName('Gateways')
		.addPanel( createPanel('draginoMNSdb', 'mnsMain')
		    .setName('Gateways')
			.addLabel(createLabel('gwSN'))
		    .addBlock(createBlock('gwSN'))
		    .addBlock(createBlock('gwStatus'))
		)
	)

	.addGroup( createGroup()
		.setName('gwGroup')
		.addPanel( createPanel('draginoMNSdb', 'gwGroup')	
			.setName('gwGroup')
		)
		.addPanel( createPanel('draginoMNSdb', 'gwConfig')	
			.setName('config')
			.setCreateEnabled(false)
		)
	)
